print'Content-type:text/html\r\n\r\n'  
print'<html>'
print'<body>'
print'<form action="ecommerce2.py" method = "post" target ="_blank">'
print'<select name="mobiles">'
print'<option></option>'
print'<option value = "vivo">vivo</option>'
print'<option value = "oppo">oppo</option>'
print'<option value = "sony">sony</option>'
print'<option selected value = "samsung">samsung</option>'
print'<option value = "lg">lg</option>'
print'<option value = "nokia">nokia</option>'
print'</select><br><br>'
print'<textarea name="text_content" cols="40" rows="4">'
print'</textarea>'
print'<input type="submit" value="Buy"/>'
print'</form>'
print'</body>'
print'</html>'

